export const providedContent = {
  title: "Social Media Dashboard",
  totalFollowers: {
    title: "Total Followers: ",
    amount: "23,004",
  },
  toggleText: {
    dark: "Light Mode",
    light: "Dark Mode",
  },
  mainView: [
    {
      handle: "@nathanf",
      label: "Followers",
      site: "facebook",
      value: 1987,
      valueType: "number",
      variation: "+",
      variationValue: 12,
      when: "Today",
    },
    {
      handle: "@nathanf",
      label: "Followers",
      site: "twitter",
      value: 1044,
      valueType: "number",
      variation: "+",
      variationValue: 99,
      when: "Today",
    },
    {
      handle: "@nathanf",
      label: "Followers",
      site: "instagram",
      value: 11000,
      valueType: "number",
      variation: "+",
      variationValue: 1099,
      when: "Today",
    },
    {
      handle: "Nathan F.",
      label: "Subscribers",
      site: "youtube",
      value: 8239,
      valueType: "number",
      variation: "-",
      variationValue: 144,
      when: "Today",
    },
  ],
  overview: [
    {
      title: "Page Views",
      value: 87,
      variationAmount: 3,
      variationType: "fraction",
      variation: "+",
      site: "facebook",
    },
    {
      title: "Likes",
      value: 52,
      variationAmount: 2,
      variationType: "fraction",
      variation: "+",
      site: "facebook",
    },
    {
      title: "Likes",
      value: 5462,
      variationAmount: 2257,
      variationType: "fraction",
      variation: "+",
      site: "twitter",
    },
    {
      title: "Profile Views",
      value: 52874,
      variationAmount: 1375,
      variationType: "fraction",
      variation: "+",
      site: "twitter",
    },
    {
      title: "Retweets",
      value: 117,
      variationAmount: 303,
      variationType: "fraction",
      variation: "+",
      site: "instagram",
    },
    {
      title: "Likes",
      value: 507,
      variationAmount: 553,
      variationType: "fraction",
      variation: "+",
      site: "instagram",
    },
    {
      title: "Likes",
      value: 107,
      variationAmount: 19,
      variationType: "fraction",
      variation: "-",
      site: "youtube",
    },
    {
      title: "Total Views",
      value: 1407,
      variationAmount: 12,
      variationType: "fraction",
      variation: "-",
      site: "youtube",
    },
  ],
};
